--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ZulfahmiFjr/SoulWell
build-by-default: true
branches:
- master
projects:
  SoulWell:
    path: ""
    icon: icon.png
    libs:
      - src: muqsit/InvMenu/InvMenu
        version: ^4.6.6
        branch: "pm5"
    lint:
       phpstan: false
...
