name: SoulWell
main: ZulfahmiFjr\SoulWell\Main
author: ZulfahmiFjr
description: Lucky Draw Plugin inspired by Hypixel's Soul Well
version: 1.5
api: 5.27.0

commands:
    soulwell:
        description: SoulWell plugin
        permission: soulwell.command
    addwell:
        description: Add SoulWell block
        permission: soulwell.command
    addsouls:
        description: Add Soul Keys player
        permission: soulwell.command

permissions:
    soulwell.command:
        default: true
